@startuml
title Диаграмма контейнеров банка Стандарт

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Person(client, "Клиент банка", "")
Person(callCentreEmp, "Сотрудник кол-центра", "")
Person(depositBackOffice, "Сотрудник депозитов", "")
Person(creditBackOffice, "Сотрудник кредитов", "")
Person(frontOffice, "Сотрудник отделения", "")

System(bankSys, "IT-система банка Стандарт")
System(callCentreSys, "Система кол-центра", "")
System_Ext(telecomOperator, "Телеком-оператор", "Внешний оператор по отправке СМС")

Container_Boundary(bankSys, "IT-система банка Стандарт") {
'  services
    Container(apiGateway, "API-шлюз", "Nginx", "")
    Container(internetBank, "Интернет-банк", "ASP.NET MVC", "Открытие депозитов и накопительных счетов")
    Container(bankMainframeClient, "Десктопный клиент АБС", "Delphi", "Основная система, выполняющая банковские операции")
    Container(webSite, "Сайт банка", "React.js, PHP", "Текущие ставки по депозитам и форма для заявки")
    Container(smsGate, "СМС-шлюз", "", "Отправка СМС")
    Container(ratesService, "Сервис ставок", "PHP", "Расчет ставок в зависимости ставки рефинансирования и количество кредитов и депозитов в банке")
    Container(productService, "Сервис продуктов (депозитов)", "PHP", "Управление продуктом Депозит и его параметрами")
    Container(applicationService, "Сервис заявок", "PHP", "Управление процессом подачи и обработки заявок на открытие депозита")
'  databases
    ContainerDb(bankMainframeDB, "БД АБС", "Oracle", "")
    ContainerDb(internetBankDB, "БД интернет-банка", "MS SQL", "")
    ContainerDb(ratesServiceDB, "БД cервиса ставок", "PostgreSQL", "")
    ContainerDb(productServiceDB, "БД сервиса продуктов", "PostgreSQL", "")
    ContainerDb(applicationServiceDB, "БД сервиса заявок", "PostgreSQL", "")
'  topics
  ContainerQueue(smsTopic, "Топик СМС", "Kafka")
  ContainerQueue(applicationTopic, "Топик заявок", "Kafka")
}

Rel(client, webSite, "Выбирает депозит, создает заявку, подтверждает заявку")
Rel(webSite, apiGateway, "Получает данные по продуктам и ставкам")
Rel(webSite, callCentreSys, "Создает заявку на обратный звонок")
Rel(callCentreEmp, callCentreSys, "Обработывает заявки на звонок, создает заявки на депозит")
Rel(callCentreSys, applicationTopic, "Посылает заявку на депозит")
Rel(applicationService, applicationTopic, "Получает заявку на депозит")
Rel(depositBackOffice, bankMainframeClient, "Подтверждает заявки на депозит")
Rel(bankMainframeClient, apiGateway, "Управляет продуктами, ставками и заявками на депозит")
Rel(applicationService, smsTopic, "Посылает СМС")
Rel(frontOffice, bankMainframeClient, "Создает депозит, оформляет документы")

Rel(client, internetBank, "Выбирает депозит, создает заявку, подтверждает заявку")
Rel(internetBank, apiGateway, "Получает данные по продуктам и ставкам, создает заявки")

Rel(apiGateway, smsGate, "Маршрутизирует запросы")
Rel(apiGateway, ratesService, "Маршрутизирует запросы")
Rel(apiGateway, productService, "Маршрутизирует запросы")
Rel(apiGateway, applicationService, "Маршрутизирует запросы")

Rel(smsGate, smsTopic, "Получает СМС")
Rel(smsGate, telecomOperator, "СМС-сообщение")
Rel(telecomOperator, client, "СМС-сообщение")

Rel(creditBackOffice, bankMainframeClient, "Рассчитывает ставки по депозитам")

Rel(bankMainframeClient, bankMainframeDB, "Читает/пишет данные")
Rel(internetBank, internetBankDB, "Читает/пишет данные")
Rel(ratesService, ratesServiceDB, "Читает/пишет данные")
Rel(productService, productServiceDB, "Читает/пишет данные")
Rel(applicationService, applicationServiceDB, "Читает/пишет данные")

@enduml