@startuml
title Диаграмма контейнеров банка Стандарт

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Person(client, "Клиент банка", "")
Person(callCentreEmp, "Сотрудник кол-центра", "")
Person(depositBackOffice, "Сотрудник депозитов", "")
Person(creditBackOffice, "Сотрудник кредитов", "")
Person(frontOffice, "Сотрудник отделения", "")

System(bankSys, "IT-система банка Стандарт")
System(callCentreSys, "Система кол-центра", "")
System_Ext(telecomOperator, "Телеком-оператор", "Внешний оператор по отправке СМС")

Container_Boundary(bankSys, "IT-система банка Стандарт") {
'  services
    Container(apiGateway, "API-шлюз", "Nginx", "")
    Container(internetBank, "Интернет-банк", "ASP.NET MVC", "Открытие депозитов и накопительных счетов")
    Container(bankMainframe, "АБС", "Delphi", "Основная система, выполняющая банковские операции")
    Container(webSite, "Сайт банка", "React.js, PHP", "Текущие ставки по депозитам и форма для заявки")
    Container(smsGate, "СМС-шлюз", "", "Отправка СМС")

    Container(ratesService, "Сервис ставок", "PHP", "Расчет ставок в зависимости ставки рефинансирования и количество кредитов и депозитов в банке")
    Container(productService, "Сервис продуктов (депозитов)", "PHP", "Управление продуктом Депозит и его параметрами")
    Container(appliactionService, "Сервис заявок", "PHP", "Управление процессом подачи и обработки заявок на открытие депозита")
'  databases
    ContainerDb(bankMainframeDB, "БД АБС", "Oracle", "")
    ContainerDb(internetBankDB, "БД интернет-банка", "MS SQL", "")
    ContainerDb(ratesServiceDB, "БД cервиса ставок", "PostgreSQL", "")
    ContainerDb(productServiceDB, "БД сервиса продуктов", "PostgreSQL", "")
    ContainerDb(appliactionServiceDB, "БД сервиса заявок", "PostgreSQL", "")

'  Container(WebApp, "Web Application", "JavaScript, React", "Handles user interactions")
''  services
'  Container(UserService, "User Management Service", "Go", "Manages users")
'  Container(SensorService, "Sensor Management Service", "Go", "Manages sensors")
'  Container(TelemetryService, "Telemetry Monitoring Service", "Go", "Monitors and stores telemetry")
''  databases
'  ContainerDb(TelemetryDatabase, "Telemetry Database", "PostgreSQL", "Stores telemetry data")
''  topics
'  ContainerQueue(SensorControlTopic, "Sensor Control Topic", "MQTT")
'  ContainerQueue(SensorStateTopic, "Sensor State Topic", "MQTT")
'  ContainerQueue(SensorTelemetryTopic, "Sensor Telemetry Topic", "MQTT")
'  ContainerQueue(ServiceStateTopic, "Service State Topic", "MQTT")
'  ContainerQueue(ServiceTelemetryTopic, "Service Telemetry Topic", "MQTT")
}

Rel(client, webSite, "Выбор депозита, создание заявки, подтверждение заявки")
Rel(client, internetBank, "Выбор депозита, создание заявки")
Rel(internetBank, smsGate, "СМС-подтверждение")
Rel(internetBank, bankMainframe, "Получение ставок, Заявка на депозит")
Rel(webSite, bankMainframe, "Получение ставок")
Rel(webSite, callCentreSys, "Заявка на обратный звонок")
Rel(callCentreEmp, callCentreSys, "Обработка заявок, внесение подтвержденных условий")
Rel(client, callCentreEmp, "Подтверждение условий депозита")
Rel(callCentreSys, bankMainframe, "Заявка на депозит")
Rel(depositBackOffice, bankMainframe, "Подтверждение заявки на депозит")
Rel(bankMainframe, smsGate, "СМС-уведомление")
Rel(smsGate, telecomOperator, "СМС-сообщение")
Rel(telecomOperator, client, "СМС-сообщение")
Rel(client, frontOffice, "Обращение в отдедение")
Rel(frontOffice, bankMainframe, "Создание депозита, оформление документов")
Rel(creditBackOffice, bankMainframe, "Информация о ставке рефинансирования")
Rel(bankMainframe, bankMainframe, "Расчет ставок по депозитам")

Rel(bankMainframe, bankMainframeDB, "Читает/пишет данные")
Rel(internetBank, internetBankDB, "Читает/пишет данные")

@enduml